platform :ios, '15.0'
use_frameworks!
project 'LegacySmoke.xcodeproj'

source 'https://cdn.cocoapods.org/'

target 'LegacySmoke' do
  pod 'BidscubeSDKAppLovinLegacy', :path => '..'
end

target 'BidscubeSDKAppLovinTestApp' do
  pod 'BidscubeSDKAppLovin', :path => '..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      deployment_target = target.name == 'BidscubeSDKAppLovinLegacy' ? '14.0' : '15.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
